### ISSUE TITLE
Your example of NanoCross cann't run

### ISSUE THREAD

**Issue by maochuangxue** [zuoquanchen/NanoCross#1]
I have found that the script and data which you provide were not able to run. It seem that you didn't give the final version.

**Comment by okendojo** [comment]
which information did you feed under `-C chromosome information`, could you share the command you used to run the analysis?

**Comment by zuoquanchen** [comment]
Our pipline is just a concrete analysis idea and process, not a complete package of software. You need to configure all the software and environment to make it work.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送


发件人: maochuangxue ***@***.***>
发送时间: Monday, February 20, 2023 9:41:32 AM
收件人: zuoquanchen/NanoCross ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zuoquanchen/NanoCross] Your example of NanoCross cann't run (Issue #1)


I have found that the script and data which you provide were not able to run. It seem that you didn't give the final version.

―
